/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"encoding/json"
)

// PostAppSessions - Creates a new Individual Application Session Context resource
func PostAppSessions(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	var ascRespData AppSessionContextRespData
	ascRespData = AppSessionContextRespData {
		SuppFeat: "2",
	}
	var appSessionContext AppSessionContext
	appSessionContext.AscRespData = &ascRespData

	json.NewEncoder(w).Encode(&appSessionContext)
	w.WriteHeader(http.StatusCreated)

	fmt.Printf("appSessionContext: %+v\n", appSessionContext)
}
