/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// EventsNotification - describes the notification of a matched event
type EventsNotification struct {

	AccessType *AccessType `json:"accessType,omitempty"`

	AnGwAddr *AnGwAddress `json:"anGwAddr,omitempty"`

	EvSubsUri string `json:"evSubsUri"`

	EvNotifs []AfEventNotification `json:"evNotifs"`

	FailedResourcAllocReports []ResourcesAllocationInfo `json:"failedResourcAllocReports,omitempty"`

	PlmnId *PlmnId `json:"plmnId,omitempty"`

	QncReports []QosNotificationControlInfo `json:"qncReports,omitempty"`

	RatType *RatType `json:"ratType,omitempty"`

	UsgRep *AccumulatedUsage `json:"usgRep,omitempty"`
}
