/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AfRoutingRequirementRm - this data type is defined in the same way as the AfRoutingRequirement data type, but with the OpenAPI nullable property set to true and the spVal and tempVals attributes defined as removable.
type AfRoutingRequirementRm struct {

	AppReloc bool `json:"appReloc,omitempty"`

	RouteToLocs []RouteToLocation `json:"routeToLocs,omitempty"`

	SpVal *SpatialValidityRm `json:"spVal,omitempty"`

	TempVals []TemporalValidity `json:"tempVals,omitempty"`

	UpPathChgSub *UpPathChgEvent `json:"upPathChgSub,omitempty"`
}
