/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Snssai struct {

	Sst int32 `json:"sst"`

	Sd string `json:"sd,omitempty"`
}
