/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AppSessionContextReqData - Identifies the service requirements of an Individual Application Session Context.
type AppSessionContextReqData struct {

	// Contains an AF application identifier.
	AfAppId string `json:"afAppId,omitempty"`

	AfRoutReq *AfRoutingRequirement `json:"afRoutReq,omitempty"`

	// Contains an identity of an application service provider.
	AspId string `json:"aspId,omitempty"`

	// string identifying a BDT Reference ID as defined in subclause 5.3.3 of 3GPP TS 29.154.
	BdtRefId string `json:"bdtRefId,omitempty"`

	Dnn string `json:"dnn,omitempty"`

	EvSubsc *EventsSubscReqData `json:"evSubsc,omitempty"`

	MedComponents map[string]MediaComponent `json:"medComponents,omitempty"`

	IpDomain string `json:"ipDomain,omitempty"`

	// indication of MPS service request
	MpsId string `json:"mpsId,omitempty"`

	NotifUri string `json:"notifUri"`

	SliceInfo *Snssai `json:"sliceInfo,omitempty"`

	// Contains an identity of a sponsor.
	SponId string `json:"sponId,omitempty"`

	SponStatus *SponsoringStatus `json:"sponStatus,omitempty"`

	Supi string `json:"supi,omitempty"`

	SuppFeat string `json:"suppFeat"`

	UeIpv4 string `json:"ueIpv4,omitempty"`

	UeIpv6 string `json:"ueIpv6,omitempty"`

	UeMac string `json:"ueMac,omitempty"`
}
