/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AfEventSubscription - describes the event information delivered in the subscription
type AfEventSubscription struct {

	Event *AfEvent `json:"event"`

	NotifMethod *AfNotifMethod `json:"notifMethod,omitempty"`
}
