/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AfEventNotification - describes the event information delivered in the notification
type AfEventNotification struct {

	Event *AfEvent `json:"event"`

	Flows []Flows `json:"flows,omitempty"`
}
