/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AppSessionContext - Represents an Individual Application Session Context resource.
type AppSessionContext struct {

	AscReqData *AppSessionContextReqData `json:"ascReqData,omitempty"`

	AscRespData *AppSessionContextRespData `json:"ascRespData,omitempty"`

	EvsNotif *EventsNotification `json:"evsNotif,omitempty"`
}
