/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MediaSubComponentRm - This data type is defined in the same way as the MediaSubComponent data type, but with the OpenAPI nullable property set to true. Removable attributes marBwDland marBwUl are defined with the corresponding removable data type.
type MediaSubComponentRm struct {

	EthfDescs []EthFlowDescription `json:"ethfDescs,omitempty"`

	FNum int32 `json:"fNum"`

	FDescs []string `json:"fDescs,omitempty"`

	FStatus *FlowStatus `json:"fStatus,omitempty"`

	MarBwDl string `json:"marBwDl,omitempty"`

	MarBwUl string `json:"marBwUl,omitempty"`

	// this data type is defined in the same way as the TosTrafficClass data type, but with the OpenAPI nullable property set to true
	TosTrCl string `json:"tosTrCl,omitempty"`

	FlowUsage *FlowUsage `json:"flowUsage,omitempty"`
}
