/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MediaSubComponent - Identifies a media subcomponent
type MediaSubComponent struct {

	EthfDescs []EthFlowDescription `json:"ethfDescs,omitempty"`

	FNum int32 `json:"fNum"`

	FDescs []string `json:"fDescs,omitempty"`

	FStatus *FlowStatus `json:"fStatus,omitempty"`

	MarBwDl string `json:"marBwDl,omitempty"`

	MarBwUl string `json:"marBwUl,omitempty"`

	// 2-octet string, where each octet is encoded in hexadecimal representation. The first octet contains the IPv4 Type-of-Service or the IPv6 Traffic-Class field and the second octet contains the ToS/Traffic Class mask field.
	TosTrCl string `json:"tosTrCl,omitempty"`

	FlowUsage *FlowUsage `json:"flowUsage,omitempty"`
}
