/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AppSessionContextUpdateData - Identifies the modifications to an Individual Application Session Context and may include the modifications to the sub-resource Events Subscription.
type AppSessionContextUpdateData struct {

	// Contains an AF application identifier.
	AfAppId string `json:"afAppId,omitempty"`

	AfRoutReq *AfRoutingRequirementRm `json:"afRoutReq,omitempty"`

	// Contains an identity of an application service provider.
	AspId string `json:"aspId,omitempty"`

	// string identifying a BDT Reference ID as defined in subclause 5.3.3 of 3GPP TS 29.154.
	BdtRefId string `json:"bdtRefId,omitempty"`

	EvSubsc *EventsSubscReqDataRm `json:"evSubsc,omitempty"`

	MedComponents map[string]MediaComponentRm `json:"medComponents,omitempty"`

	// indication of MPS service request
	MpsId string `json:"mpsId,omitempty"`

	// Contains an identity of a sponsor.
	SponId string `json:"sponId,omitempty"`

	SponStatus *SponsoringStatus `json:"sponStatus,omitempty"`
}
