/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// TemporalValidity - Indicates the time interval(s) during which the AF request is to be applied
type TemporalValidity struct {

	StartTime time.Time `json:"startTime,omitempty"`

	StopTime time.Time `json:"stopTime,omitempty"`
}
