/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MediaComponentRm - This data type is defined in the same way as the MediaComponent data type, but with the OpenAPI nullable property set to true
type MediaComponentRm struct {

	// Contains an AF application identifier.
	AfAppId string `json:"afAppId,omitempty"`

	AfRoutReq *AfRoutingRequirementRm `json:"afRoutReq,omitempty"`

	// Represents the content version of some content.
	ContVer int32 `json:"contVer,omitempty"`

	Codecs []string `json:"codecs,omitempty"`

	FStatus *FlowStatus `json:"fStatus,omitempty"`

	MarBwDl string `json:"marBwDl,omitempty"`

	MarBwUl string `json:"marBwUl,omitempty"`

	MedCompN int32 `json:"medCompN"`

	MedSubComps map[string]MediaSubComponentRm `json:"medSubComps,omitempty"`

	MedType *MediaType `json:"medType,omitempty"`

	MirBwDl string `json:"mirBwDl,omitempty"`

	MirBwUl string `json:"mirBwUl,omitempty"`

	ResPrio *ReservPriority `json:"resPrio,omitempty"`
}
